# =============================================================================
# DINOEncoderDecoder - 方案三配置
# 
# 架构特点:
# - 使用 DINOv3 作为唯一编码器 (无 Restormer Encoder)
# - 多尺度特征提取 (Layer 4/8/12)
# - FPN 风格解码器 + 块效应处理
# - 可选 LoRA 微调支持
# - 残差连接输出
# =============================================================================

name: LowLight_DINOEncoderDecoder_192_2_80k
model_type: DINOImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 42

# =============================================================================
# 数据集配置
# =============================================================================
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: ./datasets/LOL-v2/Real_captured/Train/Normal
    dataroot_lq: ./datasets/LOL-v2/Real_captured/Train/Low
    geometric_augs: true

    filename_tmpl: "{}"
    io_backend:
      type: disk

    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2

    mini_batch_sizes: [2]
    iters: [80000]
    gt_size: 192
    gt_sizes: [192]

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: ./datasets/LOL-v2/Real_captured/Test/Normal
    dataroot_lq: ./datasets/LOL-v2/Real_captured/Test/Low
    io_backend:
      type: disk

# =============================================================================
# 网络架构 - DINOEncoderDecoder (方案三)
# =============================================================================
network_g:
  type: DINOEncoderDecoder
  inp_channels: 3
  out_channels: 3
  
  # ===== DINOv3 编码器配置 =====
  dino_model: dinov3_vithplus16
  dino_gamma: 0.35
  dino_local_path: E:\2024HZF\Models\facebook\dinov3-vith16plus-pretrain-lvd1689m
  extract_layers: [4, 8, 12]          # 多尺度特征提取层
  
  # ===== FPN 解码器配置 =====
  hidden_dims: [384, 192, 96, 48]     # 解码器各层通道数
  
  # ===== 块效应处理 =====
  use_boundary_blend: true            # 启用边界混合
  
  # ===== LoRA 微调 (可选) =====
  use_lora: false                     # 是否启用 LoRA
  lora_r: 16                          # LoRA 秩
  lora_alpha: 32                      # LoRA alpha
  lora_dropout: 0.1                   # LoRA dropout

# =============================================================================
# 路径配置
# =============================================================================
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# =============================================================================
# 训练配置
# =============================================================================
train:
  total_iter: 80000
  warmup_iter: 2000
  use_grad_clip: true
  save_models: false              # 禁用中间 checkpoint 保存，只保留最佳模型

  ema_decay: 0.999

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [40000, 40000]
    restart_weights: [1, 0.5]
    eta_mins: [!!float 1e-4, !!float 1e-7]

  mixing_augs:
    mixup: true
    mixup_beta: 1.0
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 5e-4
    betas: [0.9, 0.999]

  # ===== 分层学习率 (推荐用于 LoRA 微调) =====
  layerwise_lr:
    enabled: false                    # 启用分层学习率
    dino_lr_ratio: 0.05               # DINO 参数学习率 = base_lr * 0.05
    fusion_lr_ratio: 1.0              # Fusion 模块学习率
    decoder_lr_ratio: 1.0             # Decoder 学习率

  # ===== 复合损失配置 =====
  composite_opt:
    lambda_rec: 1.0                   # Charbonnier 重建损失
    lambda_ssim: 0.8                  # SSIM 结构损失
    lambda_per: 0.05                  # VGG 感知损失
    lambda_sem: 0.02                  # DINO 语义损失
    use_perceptual: true
    use_semantic: true
    dino_gamma: 0.35
    # 语义损失高级配置
    semantic_distance: cosine         # 'l1', 'l2', 'cosine'
    semantic_layers: [12]             # 使用哪些 DINO 层计算损失
    semantic_normalize: true          # 特征归一化

# =============================================================================
# 验证配置
# =============================================================================
val:
  window_size: 8
  val_freq: !!float 2e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 8

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

  early_stopping:
    enabled: true
    patience: 30
    monitor: psnr

# =============================================================================
# 日志配置
# =============================================================================
logger:
  print_freq: 500
  save_checkpoint_freq: false     # false 禁用中间保存，数字则间隔保存
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# =============================================================================
# 分布式训练配置
# =============================================================================
dist_params:
  backend: nccl
  port: 29500
