# general settings
name: LowLight_DINORestormer
model_type: DINOImageRestorationModel
scale: 1
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: ./datasets/LOL-v2/Real_captured/Train/Normal
    dataroot_lq: ./datasets/LOL-v2/Real_captured/Train/Low
    geometric_augs: true

    filename_tmpl: "{}"
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4  # Reduced due to DINO memory usage

    ### ------- Training on single fixed-patch size 128x128 (divisible by 16 for DINOv3) ---------
    mini_batch_sizes: [4]
    iters: [300000]
    gt_size: 128  # Must be divisible by 16 (DINOv3 patch size) and 8 (Restormer downsampling)
    gt_sizes: [128]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: ./datasets/LOL-v2/Real_captured/Test/Normal
    dataroot_lq: ./datasets/LOL-v2/Real_captured/Test/Low
    io_backend:
      type: disk

# network structures
network_g:
  type: DINOGuidedRestormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 4
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  # DINOv3 guidance settings
  dino_model: dinov3_vithplus16  # Options: dinov3_vits16, dinov3_vitsplus16, dinov3_vitb16, dinov3_vitl16, dinov3_vithplus16
  dino_gamma: 0.4  # Gamma correction for low-light preprocessing (0.3-0.5)
  dino_local_path: E:\2024HZF\Models\facebook\dinov3-vith16plus-pretrain-lvd1689m
  use_dino_guidance: true  # Set to false to disable DINO guidance

# path
path:
  pretrain_network_g: ~  # Can load pretrained Restormer weights
  strict_load_g: false  # Set to false to allow loading Restormer weights without DINO keys
  resume_state: ~

# training settings
train:
  total_iter: 300000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles.
  # 1st cycle: fixed 3e-4 LR for 92k iters.
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]
    restart_weights: [1, 1]
    eta_mins: [0.0003, 0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  # losses - DINO Composite Loss
  # Combines: Charbonnier (pixel) + SSIM (structure) + Perceptual (VGG) + DINO Semantic
  composite_opt:
    lambda_rec: 1.0      # Charbonnier reconstruction loss weight
    lambda_ssim: 1.0     # SSIM structural similarity loss weight
    lambda_per: 0.1      # VGG perceptual loss weight
    lambda_sem: 0.05     # DINO semantic consistency loss weight
    use_perceptual: true # Enable VGG perceptual loss
    use_semantic: true   # Enable DINO semantic loss (uses network's DINO)
    dino_gamma: 0.4      # Gamma correction for DINO preprocessing

  # Fallback pixel loss (used if composite_opt is removed)
  # pixel_opt:
  #   type: L1Loss
  #   loss_weight: 1
  #   reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 4e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false  # Calculate in RGB space

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
