# general settings
name: Restormer_LOLv2_prog_cos_25k
model_type: ImageCleanModel
scale: 1
num_gpu: 1
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: TrainSet_LOLv2
    type: Dataset_PairedImage
    dataroot_gt: ./datasets/LOL-v2/Real_captured/Train/Normal
    dataroot_lq: ./datasets/LOL-v2/Real_captured/Train/Low
    geometric_augs: true

    filename_tmpl: "{}"
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 48

    ### -------------Progressive training (方案 A - 25k 闪电版)-----
    # 物理 Batch Size
    mini_batch_sizes: [48, 32, 20, 12, 8, 4]
    # 针对 LOL-v2 小数据集精简的迭代次数
    iters: [12000, 5000, 3000, 2500, 1500, 1000]
    gt_size: 384
    gt_sizes: [128, 160, 192, 256, 320, 384]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet_LOLv2
    type: Dataset_PairedImage
    dataroot_gt: ./datasets/LOL-v2/Real_captured/Test/Normal
    dataroot_lq: ./datasets/LOL-v2/Real_captured/Test/Low
    io_backend:
      type: disk

# network structures
network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 4
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False
  use_checkpoint: True

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 25000
  warmup_iter: -1
  use_grad_clip: true

  # 针对单卡 4090 优化 (方案 A)
  mini_accumulation_steps: [1, 1, 2, 3, 4, 8]
  accumulation_steps: 1

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  # 快速退火策略
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [12000, 13000]
    restart_weights: [1, 1]
    eta_mins: [0.0003, 0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: 500 # 提高验证频率，捕捉最佳甜点
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 8

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100 # 加快打印频率，缓解焦虑
  save_checkpoint_freq: 500
  use_tb_logger: true
  wandb:
    project: Restormer_LOLv2
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
