# general settings
name: Restormer_LOLv2_prog_cos_100k
model_type: ImageCleanModel
scale: 1
num_gpu: 1
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: TrainSet_LOLv2
    type: Dataset_PairedImage
    dataroot_gt: ./datasets/LOL-v2/Real_captured/Train/Normal
    dataroot_lq: ./datasets/LOL-v2/Real_captured/Train/Low
    geometric_augs: true

    filename_tmpl: "{}"
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 48

    ### -------------Progressive training (方案 A - 100k 快速版)-----
    # 物理 Batch Size (基于 24G 显存实测，留有约 2G 缓冲)
    mini_batch_sizes: [48, 32, 20, 12, 8, 4]
    # mini_accumulation_steps: [1, 1, 2, 3, 4, 8]
    # 按比例分配 100k 迭代次数
    iters: [40000, 23000, 14000, 10000, 8000, 5000]

    gt_size: 384
    gt_sizes: [128, 160, 192, 256, 320, 384]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet_LOLv2
    type: Dataset_PairedImage
    dataroot_gt: ./datasets/LOL-v2/Real_captured/Test/Normal
    dataroot_lq: ./datasets/LOL-v2/Real_captured/Test/Low
    io_backend:
      type: disk

# network structures
network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 4
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False
  use_checkpoint: True # 开启梯度检查点以支持大 Batch

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 100000 # 总迭代次数
  warmup_iter: -1
  use_grad_clip: true

  # 针对单卡 4090 优化 (方案 A：平衡速度与质量)
  # 目标等效总 Batch Size 为 32~48
  mini_accumulation_steps: [1, 1, 2, 3, 4, 8]

  # 默认保底值
  accumulation_steps: 1

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  # 学习率周期与 iters 对齐
  # 1st cycle: 固定 3e-4 LR 跑完 Patch 128 阶段 (40k)
  # 2nd cycle: 其它阶段执行余弦退火 (60k)
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [40000, 60000]
    restart_weights: [1, 1]
    eta_mins: [0.0003, 0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 2e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 8

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: Restormer_LOLv2
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
