# general settings
name: Restormer_LOLv2_256_16_cos_25k_HalfLR
model_type: ImageCleanModel
scale: 1
num_gpu: 1
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: TrainSet_LOLv2
    type: Dataset_PairedImage
    dataroot_gt: ./datasets/LOL-v2/Real_captured/Train/Normal
    dataroot_lq: ./datasets/LOL-v2/Real_captured/Train/Low
    geometric_augs: true

    filename_tmpl: "{}"
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 12
    batch_size_per_gpu: 8 # 【物理 Batch 保持 8】

    ### ------- Training on patch size 256x256 ---------
    iters: [50000]
    mini_batch_sizes: [8] # 【同步物理 Batch】
    gt_size: 256 # 【已修改为 256】
    gt_sizes: [256] # 【已修改为 256】
    ### ------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: true

  val:
    name: ValSet_LOLv2
    type: Dataset_PairedImage
    dataroot_gt: ./datasets/LOL-v2/Real_captured/Test/Normal
    dataroot_lq: ./datasets/LOL-v2/Real_captured/Test/Low
    io_backend:
      type: disk

# network structures
network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 4
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False
  use_checkpoint: True

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 50000
  warmup_iter: 2000

  # 开启梯度累计，物理 Batch 8 * 2 = 16 等效 Batch
  accumulation_steps: 2 # 【累加 2 次】
  mini_accumulation_steps: [2] # 【同步累加】

  optim_g:
    type: AdamW
    lr: !!float 1.5e-4 # 【已减半】匹配等效 Batch 16
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  # 余弦退火调度器
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [50000]
    restart_weights: [1]
    eta_mins: [0.0000025] # 【同步减半】

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 1e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 16

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: Restormer_LOLv2
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
